name: CI

on:
  workflow_dispatch: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:   
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build
      env:
        BUILD_CONFIG: 'Release'
        SOLUTION: 'DarkUI.sln'
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG 


