name: CI

on:
  workflow_dispatch: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  BUILD_CONFIG: Release
  SOLUTION: DarkUI.sln 

jobs:
  build:   

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore ${{env.SOLUTION}}
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Debuging Script
      run: |
        echo Home: $HOME
        echo SOLUTION: ${{env.SOLUTION}}
        echo BUILD_CONFIG: ${{env.BUILD_CONFIG}}
        #dir

    - name: Build 
      run: dotnet build ${{env.SOLUTION}} --configuration ${{env.BUILD_CONFIG}} --no-restore

    - name: Publish nuget
      run: dotnet nuget push "DarkUI\bin\Release\*nupkg" -k {GITHUB_TOKEN}  -s "github"
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_PUBLISH }}
