name: CI
on:
  workflow_dispatch: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  build:   
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'DarkUI.sln'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore ${SOLUTION}
      run: echo "1: ${SOLUTION}"
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build
      run: dotnet build DarkUI.sln --configuration Release

    - name: Debuging Script
      run: |
        echo "Home: ${HOME}"
        echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
        echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
        echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
        echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
        echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
        echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
        echo "GITHUB_SHA: ${GITHUB_SHA}"
        echo "GITHUB_REF: ${GITHUB_REF}"
        echo "SOLUTION: ${SOLUTION}"
        echo "BUILD_CONFIG: ${BUILD_CONFIG}"

    - name: Build Config
      run: dotnet build "${SOLUTION}" --configuration "${BUILD_CONFIG}" --no-restore
